In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Titanic-Dataset.csv")

# Question 1.

```
Q1
Show:

Female passengers
AND
Age > 30

Return:

Name
Age

using loc.
```

In [5]:
df.loc[

    ((df["Sex"] == "female")

      &

      (df["Age"] > 30) ),

       ["Name","Age"]



]

                                                  Name   Age
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
11                            Bonnell, Miss. Elizabeth  58.0
15                    Hewlett, Mrs. (Mary D Kingcome)   55.0
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  31.0
..                                                 ...   ...
862  Swift, Mrs. Frederick Joel (Margaret Welles Ba...  48.0
865                           Bystrom, Mrs. (Karolina)  42.0
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  47.0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0
885               Rice, Mrs. William (Margaret Norton)  39.0

[103 rows x 2 columns]

# Questions 2

```
Q2

Show passengers whose:

Pclass is 1 or 2

Return:

Name
Pclass

using isin() and loc.
```

In [7]:
df.loc[
    (df["Pclass"].isin([1,2])),
    ["Name","Pclass"]
]

                                                  Name  Pclass
1    Cumings, Mrs. John Bradley (Florence Briggs Th...       1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)       1
6                              McCarthy, Mr. Timothy J       1
9                  Nasser, Mrs. Nicholas (Adele Achem)       2
11                            Bonnell, Miss. Elizabeth       1
..                                                 ...     ...
880       Shelley, Mrs. William (Imanita Parrish Hall)       2
883                      Banfield, Mr. Frederick James       2
886                              Montvila, Rev. Juozas       2
887                       Graham, Miss. Margaret Edith       1
889                              Behr, Mr. Karl Howell       1

[400 rows x 2 columns]

# Question 3

```
Q3

Show passengers whose:

Fare between 50 and 100
AND
Survived = 1

Return:

Name
Fare
```

In [8]:
df.loc[
    ((df["Survived"] == 1)
    &
    (df["Fare"].between(50, 100))),
    ["Name","Fare"]
]

                                                  Name     Fare
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  71.2833
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  53.1000
52            Harper, Mrs. Henry Sleeper (Myna Haxtun)  76.7292
61                                 Icard, Miss. Amelie  80.0000
74                                       Bing, Mr. Lee  56.4958
..                                                 ...      ...
835                        Compton, Miss. Sara Rebecca  83.1583
838                                    Chip, Mr. Chang  56.4958
849       Goldenberg, Mrs. Samuel L (Edwiga Grabowska)  89.1042
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  52.5542
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  83.1583

[70 rows x 2 columns]